# Generated by Django 5.2.7 on 2025-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_wartawan_bukti_penerimaan_surat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wartawan',
            name='nrp',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
